// Code generated by goctl. DO NOT EDIT!
// Source: gateway.proto

package server

import (
	"context"

	"ylink/gateway/rpc/internal/logic"
	"ylink/gateway/rpc/internal/svc"
	"ylink/gateway/rpc/pb"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

func (s *GatewayServer) PlayerLogin(ctx context.Context, in *pb.PlayerLoginReq) (*pb.LoginResp, error) {
	l := logic.NewPlayerLoginLogic(ctx, s.svcCtx)
	return l.PlayerLogin(in)
}

func (s *GatewayServer) CsLogin(ctx context.Context, in *pb.CsLoginReq) (*pb.LoginResp, error) {
	l := logic.NewCsLoginLogic(ctx, s.svcCtx)
	return l.CsLogin(in)
}
