// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"call_center/db/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/db/api/api_test/:id",
				Handler: apiTestHandler(serverCtx),
			},
		},
	)
}
