// Code generated by goctl. DO NOT EDIT!
// Source: flowsrv.proto

package server

import (
	"ylink/flowsrv/rpc/internal/logic"
	"ylink/flowsrv/rpc/internal/svc"
	"ylink/flowsrv/rpc/pb"
)

type FlowsrvServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFlowsrvServer
}

func NewFlowsrvServer(svcCtx *svc.ServiceContext) *FlowsrvServer {
	return &FlowsrvServer{
		svcCtx: svcCtx,
	}
}

func (s *FlowsrvServer) Connect(in *pb.CommandReq, stream pb.Flowsrv_ConnectServer) error {
	l := logic.NewConnectLogic(stream.Context(), s.svcCtx)
	return l.Connect(in, stream)
}
