// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ylink/bff/authbff/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/player-login",
				Handler: playerLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs-login",
				Handler: csLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)
}
