// Code generated by goctl. DO NOT EDIT!
// Source: transfer.proto

package server

import (
	"context"

	"ylink/core/transfer/rpc/internal/logic"
	"ylink/core/transfer/rpc/internal/svc"
	"ylink/core/transfer/rpc/pb"
)

type TransferServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTransferServer
}

func NewTransferServer(svcCtx *svc.ServiceContext) *TransferServer {
	return &TransferServer{
		svcCtx: svcCtx,
	}
}

func (s *TransferServer) Invoke(ctx context.Context, in *pb.TransferReq) (*pb.TransferResp, error) {
	l := logic.NewInvokeLogic(ctx, s.svcCtx)
	return l.Invoke(in)
}
