// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: db_cmds.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EDbCommand int32

const (
	EDbCommand_E_DB_COMMAND_UNSPECIFIED      EDbCommand = 0
	EDbCommand_E_DB_COMMAND_PUSH_CHAT_LOG    EDbCommand = 1001 // 推送聊天日志
	EDbCommand_E_DB_COMMAND_PUSH_CHAT_RECORD EDbCommand = 1002 // 推送客服对接记录
	EDbCommand_E_DB_COMMAND_GET_CONFIG       EDbCommand = 2001 // 获取配置
	EDbCommand_E_DB_COMMAND_GET_CHAT_RECORD  EDbCommand = 2002 // 获取客服对接记录
	EDbCommand_E_DB_COMMAND_GET_CHAT_LOG     EDbCommand = 2003 // 获取日志记录
)

// Enum value maps for EDbCommand.
var (
	EDbCommand_name = map[int32]string{
		0:    "E_DB_COMMAND_UNSPECIFIED",
		1001: "E_DB_COMMAND_PUSH_CHAT_LOG",
		1002: "E_DB_COMMAND_PUSH_CHAT_RECORD",
		2001: "E_DB_COMMAND_GET_CONFIG",
		2002: "E_DB_COMMAND_GET_CHAT_RECORD",
		2003: "E_DB_COMMAND_GET_CHAT_LOG",
	}
	EDbCommand_value = map[string]int32{
		"E_DB_COMMAND_UNSPECIFIED":      0,
		"E_DB_COMMAND_PUSH_CHAT_LOG":    1001,
		"E_DB_COMMAND_PUSH_CHAT_RECORD": 1002,
		"E_DB_COMMAND_GET_CONFIG":       2001,
		"E_DB_COMMAND_GET_CHAT_RECORD":  2002,
		"E_DB_COMMAND_GET_CHAT_LOG":     2003,
	}
)

func (x EDbCommand) Enum() *EDbCommand {
	p := new(EDbCommand)
	*p = x
	return p
}

func (x EDbCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EDbCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_db_cmds_proto_enumTypes[0].Descriptor()
}

func (EDbCommand) Type() protoreflect.EnumType {
	return &file_db_cmds_proto_enumTypes[0]
}

func (x EDbCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EDbCommand.Descriptor instead.
func (EDbCommand) EnumDescriptor() ([]byte, []int) {
	return file_db_cmds_proto_rawDescGZIP(), []int{0}
}

type EDbChatType int32

const (
	EDbChatType_E_DB_CHAT_TYPE_PLAYER  EDbChatType = 0 // 玩家发言
	EDbChatType_E_DB_CHAT_TYPE_SERVICE EDbChatType = 1 // 客服发言
)

// Enum value maps for EDbChatType.
var (
	EDbChatType_name = map[int32]string{
		0: "E_DB_CHAT_TYPE_PLAYER",
		1: "E_DB_CHAT_TYPE_SERVICE",
	}
	EDbChatType_value = map[string]int32{
		"E_DB_CHAT_TYPE_PLAYER":  0,
		"E_DB_CHAT_TYPE_SERVICE": 1,
	}
)

func (x EDbChatType) Enum() *EDbChatType {
	p := new(EDbChatType)
	*p = x
	return p
}

func (x EDbChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EDbChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_db_cmds_proto_enumTypes[1].Descriptor()
}

func (EDbChatType) Type() protoreflect.EnumType {
	return &file_db_cmds_proto_enumTypes[1]
}

func (x EDbChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EDbChatType.Descriptor instead.
func (EDbChatType) EnumDescriptor() ([]byte, []int) {
	return file_db_cmds_proto_rawDescGZIP(), []int{1}
}

type EDbRecordState int32

const (
	EDbRecordState_E_DB_RECORD_STATE_REPLY      EDbRecordState = 0
	EDbRecordState_E_DB_RECORD_STATE_DISCONNECT EDbRecordState = 1
)

// Enum value maps for EDbRecordState.
var (
	EDbRecordState_name = map[int32]string{
		0: "E_DB_RECORD_STATE_REPLY",
		1: "E_DB_RECORD_STATE_DISCONNECT",
	}
	EDbRecordState_value = map[string]int32{
		"E_DB_RECORD_STATE_REPLY":      0,
		"E_DB_RECORD_STATE_DISCONNECT": 1,
	}
)

func (x EDbRecordState) Enum() *EDbRecordState {
	p := new(EDbRecordState)
	*p = x
	return p
}

func (x EDbRecordState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EDbRecordState) Descriptor() protoreflect.EnumDescriptor {
	return file_db_cmds_proto_enumTypes[2].Descriptor()
}

func (EDbRecordState) Type() protoreflect.EnumType {
	return &file_db_cmds_proto_enumTypes[2]
}

func (x EDbRecordState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EDbRecordState.Descriptor instead.
func (EDbRecordState) EnumDescriptor() ([]byte, []int) {
	return file_db_cmds_proto_rawDescGZIP(), []int{2}
}

var File_db_cmds_proto protoreflect.FileDescriptor

var file_db_cmds_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x62, 0x5f, 0x63, 0x6d, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x2a, 0xd0, 0x01, 0x0a, 0x0a, 0x45, 0x44, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41,
	0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1f, 0x0a, 0x1a, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44,
	0x5f, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x10, 0xe9,
	0x07, 0x12, 0x22, 0x0a, 0x1d, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e,
	0x44, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x4f,
	0x52, 0x44, 0x10, 0xea, 0x07, 0x12, 0x1c, 0x0a, 0x17, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x4f,
	0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47,
	0x10, 0xd1, 0x0f, 0x12, 0x21, 0x0a, 0x1c, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x4d,
	0x41, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x43,
	0x4f, 0x52, 0x44, 0x10, 0xd2, 0x0f, 0x12, 0x1e, 0x0a, 0x19, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43,
	0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x4c, 0x4f, 0x47, 0x10, 0xd3, 0x0f, 0x2a, 0x44, 0x0a, 0x0b, 0x45, 0x44, 0x62, 0x43, 0x68, 0x61,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x2a, 0x4f, 0x0a, 0x0e,
	0x45, 0x44, 0x62, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x45,
	0x5f, 0x44, 0x42, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_cmds_proto_rawDescOnce sync.Once
	file_db_cmds_proto_rawDescData = file_db_cmds_proto_rawDesc
)

func file_db_cmds_proto_rawDescGZIP() []byte {
	file_db_cmds_proto_rawDescOnce.Do(func() {
		file_db_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_cmds_proto_rawDescData)
	})
	return file_db_cmds_proto_rawDescData
}

var file_db_cmds_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_db_cmds_proto_goTypes = []interface{}{
	(EDbCommand)(0),     // 0: pb.EDbCommand
	(EDbChatType)(0),    // 1: pb.EDbChatType
	(EDbRecordState)(0), // 2: pb.EDbRecordState
}
var file_db_cmds_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_cmds_proto_init() }
func file_db_cmds_proto_init() {
	if File_db_cmds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_cmds_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_cmds_proto_goTypes,
		DependencyIndexes: file_db_cmds_proto_depIdxs,
		EnumInfos:         file_db_cmds_proto_enumTypes,
	}.Build()
	File_db_cmds_proto = out.File
	file_db_cmds_proto_rawDesc = nil
	file_db_cmds_proto_goTypes = nil
	file_db_cmds_proto_depIdxs = nil
}
