// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: db_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 配置信息
type DbConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfName  string `protobuf:"bytes,1,opt,name=conf_name,json=confName,proto3" json:"conf_name,omitempty"`
	ConfKey   string `protobuf:"bytes,2,opt,name=conf_key,json=confKey,proto3" json:"conf_key,omitempty"`
	ConfValue string `protobuf:"bytes,3,opt,name=conf_value,json=confValue,proto3" json:"conf_value,omitempty"`
}

func (x *DbConfig) Reset() {
	*x = DbConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbConfig) ProtoMessage() {}

func (x *DbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbConfig.ProtoReflect.Descriptor instead.
func (*DbConfig) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DbConfig) GetConfName() string {
	if x != nil {
		return x.ConfName
	}
	return ""
}

func (x *DbConfig) GetConfKey() string {
	if x != nil {
		return x.ConfKey
	}
	return ""
}

func (x *DbConfig) GetConfValue() string {
	if x != nil {
		return x.ConfValue
	}
	return ""
}

type ArrayConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*DbConfig `protobuf:"bytes,1,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
}

func (x *ArrayConfig) Reset() {
	*x = ArrayConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayConfig) ProtoMessage() {}

func (x *ArrayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayConfig.ProtoReflect.Descriptor instead.
func (*ArrayConfig) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ArrayConfig) GetDataList() []*DbConfig {
	if x != nil {
		return x.DataList
	}
	return nil
}

// 客服聊天记录
type DbChatLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromId    string      `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId      string      `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Content   string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TimeStamp int64       `protobuf:"varint,4,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	ChatType  EDbChatType `protobuf:"varint,5,opt,name=chat_type,json=chatType,proto3,enum=pb.EDbChatType" json:"chat_type,omitempty"`
	SessionId string      `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId    int32       `protobuf:"varint,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	IsVisitor bool        `protobuf:"varint,8,opt,name=is_visitor,json=isVisitor,proto3" json:"is_visitor,omitempty"`
}

func (x *DbChatLog) Reset() {
	*x = DbChatLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbChatLog) ProtoMessage() {}

func (x *DbChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbChatLog.ProtoReflect.Descriptor instead.
func (*DbChatLog) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{2}
}

func (x *DbChatLog) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *DbChatLog) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *DbChatLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DbChatLog) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *DbChatLog) GetChatType() EDbChatType {
	if x != nil {
		return x.ChatType
	}
	return EDbChatType_E_DB_CHAT_TYPE_PLAYER
}

func (x *DbChatLog) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DbChatLog) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *DbChatLog) GetIsVisitor() bool {
	if x != nil {
		return x.IsVisitor
	}
	return false
}

type ArrayDbChatLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*DbChatLog `protobuf:"bytes,1,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
}

func (x *ArrayDbChatLog) Reset() {
	*x = ArrayDbChatLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayDbChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayDbChatLog) ProtoMessage() {}

func (x *ArrayDbChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayDbChatLog.ProtoReflect.Descriptor instead.
func (*ArrayDbChatLog) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayDbChatLog) GetDataList() []*DbChatLog {
	if x != nil {
		return x.DataList
	}
	return nil
}

type DbChatRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string         `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServiceId string         `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	PlayerId  string         `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsVisitor bool           `protobuf:"varint,4,opt,name=is_visitor,json=isVisitor,proto3" json:"is_visitor,omitempty"`
	State     EDbRecordState `protobuf:"varint,5,opt,name=state,proto3,enum=pb.EDbRecordState" json:"state,omitempty"`
	TimeStamp int64          `protobuf:"varint,6,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	GameId    int32          `protobuf:"varint,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *DbChatRecord) Reset() {
	*x = DbChatRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbChatRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbChatRecord) ProtoMessage() {}

func (x *DbChatRecord) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbChatRecord.ProtoReflect.Descriptor instead.
func (*DbChatRecord) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{4}
}

func (x *DbChatRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DbChatRecord) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DbChatRecord) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DbChatRecord) GetIsVisitor() bool {
	if x != nil {
		return x.IsVisitor
	}
	return false
}

func (x *DbChatRecord) GetState() EDbRecordState {
	if x != nil {
		return x.State
	}
	return EDbRecordState_E_DB_RECORD_STATE_REPLY
}

func (x *DbChatRecord) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *DbChatRecord) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ArrayChatRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*DbChatRecord `protobuf:"bytes,1,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
}

func (x *ArrayChatRecord) Reset() {
	*x = ArrayChatRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayChatRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayChatRecord) ProtoMessage() {}

func (x *ArrayChatRecord) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayChatRecord.ProtoReflect.Descriptor instead.
func (*ArrayChatRecord) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ArrayChatRecord) GetDataList() []*DbChatRecord {
	if x != nil {
		return x.DataList
	}
	return nil
}

//
//命令消息
type DbCommandMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdType  EDbCommand `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=pb.EDbCommand" json:"cmd_type,omitempty"` // 命令类型
	CmdValue int32      `protobuf:"varint,2,opt,name=cmd_value,json=cmdValue,proto3" json:"cmd_value,omitempty"`                 // 通用val
	CmdStr   string     `protobuf:"bytes,3,opt,name=cmd_str,json=cmdStr,proto3" json:"cmd_str,omitempty"`                        // 通用str
	// Types that are assignable to Data:
	//	*DbCommandMsg_ArrayConfig
	//	*DbCommandMsg_ChatLog
	//	*DbCommandMsg_ChatRecord
	//	*DbCommandMsg_ArrayChatRecord
	//	*DbCommandMsg_ArrayChatLog
	Data isDbCommandMsg_Data `protobuf_oneof:"data"`
}

func (x *DbCommandMsg) Reset() {
	*x = DbCommandMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbCommandMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbCommandMsg) ProtoMessage() {}

func (x *DbCommandMsg) ProtoReflect() protoreflect.Message {
	mi := &file_db_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbCommandMsg.ProtoReflect.Descriptor instead.
func (*DbCommandMsg) Descriptor() ([]byte, []int) {
	return file_db_msg_proto_rawDescGZIP(), []int{6}
}

func (x *DbCommandMsg) GetCmdType() EDbCommand {
	if x != nil {
		return x.CmdType
	}
	return EDbCommand_E_DB_COMMAND_UNSPECIFIED
}

func (x *DbCommandMsg) GetCmdValue() int32 {
	if x != nil {
		return x.CmdValue
	}
	return 0
}

func (x *DbCommandMsg) GetCmdStr() string {
	if x != nil {
		return x.CmdStr
	}
	return ""
}

func (m *DbCommandMsg) GetData() isDbCommandMsg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *DbCommandMsg) GetArrayConfig() *ArrayConfig {
	if x, ok := x.GetData().(*DbCommandMsg_ArrayConfig); ok {
		return x.ArrayConfig
	}
	return nil
}

func (x *DbCommandMsg) GetChatLog() *DbChatLog {
	if x, ok := x.GetData().(*DbCommandMsg_ChatLog); ok {
		return x.ChatLog
	}
	return nil
}

func (x *DbCommandMsg) GetChatRecord() *DbChatRecord {
	if x, ok := x.GetData().(*DbCommandMsg_ChatRecord); ok {
		return x.ChatRecord
	}
	return nil
}

func (x *DbCommandMsg) GetArrayChatRecord() *ArrayChatRecord {
	if x, ok := x.GetData().(*DbCommandMsg_ArrayChatRecord); ok {
		return x.ArrayChatRecord
	}
	return nil
}

func (x *DbCommandMsg) GetArrayChatLog() *ArrayDbChatLog {
	if x, ok := x.GetData().(*DbCommandMsg_ArrayChatLog); ok {
		return x.ArrayChatLog
	}
	return nil
}

type isDbCommandMsg_Data interface {
	isDbCommandMsg_Data()
}

type DbCommandMsg_ArrayConfig struct {
	ArrayConfig *ArrayConfig `protobuf:"bytes,1001,opt,name=array_config,json=arrayConfig,proto3,oneof"`
}

type DbCommandMsg_ChatLog struct {
	ChatLog *DbChatLog `protobuf:"bytes,1002,opt,name=chat_log,json=chatLog,proto3,oneof"`
}

type DbCommandMsg_ChatRecord struct {
	ChatRecord *DbChatRecord `protobuf:"bytes,1003,opt,name=chat_record,json=chatRecord,proto3,oneof"`
}

type DbCommandMsg_ArrayChatRecord struct {
	ArrayChatRecord *ArrayChatRecord `protobuf:"bytes,1004,opt,name=array_chat_record,json=arrayChatRecord,proto3,oneof"`
}

type DbCommandMsg_ArrayChatLog struct {
	ArrayChatLog *ArrayDbChatLog `protobuf:"bytes,1005,opt,name=array_chat_log,json=arrayChatLog,proto3,oneof"`
}

func (*DbCommandMsg_ArrayConfig) isDbCommandMsg_Data() {}

func (*DbCommandMsg_ChatLog) isDbCommandMsg_Data() {}

func (*DbCommandMsg_ChatRecord) isDbCommandMsg_Data() {}

func (*DbCommandMsg_ArrayChatRecord) isDbCommandMsg_Data() {}

func (*DbCommandMsg_ArrayChatLog) isDbCommandMsg_Data() {}

var File_db_msg_proto protoreflect.FileDescriptor

var file_db_msg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0d, 0x64, 0x62, 0x5f, 0x63, 0x6d, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x61, 0x0a, 0x08, 0x44, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x66, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x0b, 0x41, 0x72, 0x72, 0x61, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x29, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x62, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xf7,
	0x01, 0x0a, 0x09, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x62, 0x43,
	0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x0c, 0x44, 0x62, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x62, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0f, 0x41, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x62, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x92, 0x03, 0x0a, 0x0c, 0x44, 0x62, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x44,
	0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6d, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6d, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x6d, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6d, 0x64, 0x53, 0x74, 0x72, 0x12, 0x35, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x61, 0x79,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0xe9, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48,
	0x00, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2b,
	0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0xea, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67,
	0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x34, 0x0a, 0x0b, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0xeb, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x42, 0x0a, 0x11, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0xec, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x3b, 0x0a, 0x0e, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0xed, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4c,
	0x6f, 0x67, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x4c,
	0x6f, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_msg_proto_rawDescOnce sync.Once
	file_db_msg_proto_rawDescData = file_db_msg_proto_rawDesc
)

func file_db_msg_proto_rawDescGZIP() []byte {
	file_db_msg_proto_rawDescOnce.Do(func() {
		file_db_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_msg_proto_rawDescData)
	})
	return file_db_msg_proto_rawDescData
}

var file_db_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_db_msg_proto_goTypes = []interface{}{
	(*DbConfig)(nil),        // 0: pb.DbConfig
	(*ArrayConfig)(nil),     // 1: pb.ArrayConfig
	(*DbChatLog)(nil),       // 2: pb.DbChatLog
	(*ArrayDbChatLog)(nil),  // 3: pb.ArrayDbChatLog
	(*DbChatRecord)(nil),    // 4: pb.DbChatRecord
	(*ArrayChatRecord)(nil), // 5: pb.ArrayChatRecord
	(*DbCommandMsg)(nil),    // 6: pb.DbCommandMsg
	(EDbChatType)(0),        // 7: pb.EDbChatType
	(EDbRecordState)(0),     // 8: pb.EDbRecordState
	(EDbCommand)(0),         // 9: pb.EDbCommand
}
var file_db_msg_proto_depIdxs = []int32{
	0,  // 0: pb.ArrayConfig.data_list:type_name -> pb.DbConfig
	7,  // 1: pb.DbChatLog.chat_type:type_name -> pb.EDbChatType
	2,  // 2: pb.ArrayDbChatLog.data_list:type_name -> pb.DbChatLog
	8,  // 3: pb.DbChatRecord.state:type_name -> pb.EDbRecordState
	4,  // 4: pb.ArrayChatRecord.data_list:type_name -> pb.DbChatRecord
	9,  // 5: pb.DbCommandMsg.cmd_type:type_name -> pb.EDbCommand
	1,  // 6: pb.DbCommandMsg.array_config:type_name -> pb.ArrayConfig
	2,  // 7: pb.DbCommandMsg.chat_log:type_name -> pb.DbChatLog
	4,  // 8: pb.DbCommandMsg.chat_record:type_name -> pb.DbChatRecord
	5,  // 9: pb.DbCommandMsg.array_chat_record:type_name -> pb.ArrayChatRecord
	3,  // 10: pb.DbCommandMsg.array_chat_log:type_name -> pb.ArrayDbChatLog
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_db_msg_proto_init() }
func file_db_msg_proto_init() {
	if File_db_msg_proto != nil {
		return
	}
	file_db_cmds_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_db_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbChatLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayDbChatLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbChatRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayChatRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbCommandMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_db_msg_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*DbCommandMsg_ArrayConfig)(nil),
		(*DbCommandMsg_ChatLog)(nil),
		(*DbCommandMsg_ChatRecord)(nil),
		(*DbCommandMsg_ArrayChatRecord)(nil),
		(*DbCommandMsg_ArrayChatLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_msg_proto_goTypes,
		DependencyIndexes: file_db_msg_proto_depIdxs,
		MessageInfos:      file_db_msg_proto_msgTypes,
	}.Build()
	File_db_msg_proto = out.File
	file_db_msg_proto_rawDesc = nil
	file_db_msg_proto_goTypes = nil
	file_db_msg_proto_depIdxs = nil
}
