// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cs "ylink/bff/cmdbff/api/internal/handler/cs"
	player "ylink/bff/cmdbff/api/internal/handler/player"
	"ylink/bff/cmdbff/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/player/fetch-cs-info",
				Handler: player.FetchCsInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/player/fetch-history-msg",
				Handler: player.FetchHistoryMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/player/fetch-msg",
				Handler: player.FetchMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/player/send-msg",
				Handler: player.SendMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/player/disconnect",
				Handler: player.DisconnectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/cmd"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cs/fetch-player-queue",
				Handler: cs.FetchPlayerQueueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs/connect-player",
				Handler: cs.ConnectPlayerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs/fetch-history-list",
				Handler: cs.FetchHistoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs/fetch-history-msg",
				Handler: cs.FetchHistoryMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs/fetch-msg",
				Handler: cs.FetchMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cs/send-msg",
				Handler: cs.SendMsgHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/cmd"),
	)
}
