// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//聊天信息
type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 接收者id
	Input    string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`                       // 输入内容
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ChatMsg) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

//
//玩家基本信息
type IdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                        // id
	GameId int32  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // game id
}

func (x *IdInfo) Reset() {
	*x = IdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInfo) ProtoMessage() {}

func (x *IdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInfo.ProtoReflect.Descriptor instead.
func (*IdInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *IdInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdInfo) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ArrayIdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdInfos []*IdInfo `protobuf:"bytes,1,rep,name=id_infos,json=idInfos,proto3" json:"id_infos,omitempty"`
}

func (x *ArrayIdInfo) Reset() {
	*x = ArrayIdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayIdInfo) ProtoMessage() {}

func (x *ArrayIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayIdInfo.ProtoReflect.Descriptor instead.
func (*ArrayIdInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ArrayIdInfo) GetIdInfos() []*IdInfo {
	if x != nil {
		return x.IdInfos
	}
	return nil
}

//
//聊天记录
type ChatLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                          // 聊天内容
	TimeStamp  int64  `protobuf:"varint,4,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`    // 时间戳
	GameId     int32  `protobuf:"varint,5,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`             // 游戏id
	FromPlayer bool   `protobuf:"varint,6,opt,name=from_player,json=fromPlayer,proto3" json:"from_player,omitempty"` // 是否是玩家发言
}

func (x *ChatLog) Reset() {
	*x = ChatLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatLog) ProtoMessage() {}

func (x *ChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatLog.ProtoReflect.Descriptor instead.
func (*ChatLog) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *ChatLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatLog) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ChatLog) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ChatLog) GetFromPlayer() bool {
	if x != nil {
		return x.FromPlayer
	}
	return false
}

type ArrayChatLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*ChatLog `protobuf:"bytes,1,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
}

func (x *ArrayChatLog) Reset() {
	*x = ArrayChatLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayChatLog) ProtoMessage() {}

func (x *ArrayChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayChatLog.ProtoReflect.Descriptor instead.
func (*ArrayChatLog) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ArrayChatLog) GetDataList() []*ChatLog {
	if x != nil {
		return x.DataList
	}
	return nil
}

//
//命令消息
type CommandMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdType ECommand `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=pb.ECommand" json:"cmd_type,omitempty"` // 命令类型
	CmdVal  int32    `protobuf:"varint,2,opt,name=cmd_val,json=cmdVal,proto3" json:"cmd_val,omitempty"`                     // 通用val
	CmdStr  string   `protobuf:"bytes,3,opt,name=cmd_str,json=cmdStr,proto3" json:"cmd_str,omitempty"`                      // 通用str
	// Types that are assignable to Buff:
	//	*CommandMsg_ChatMsg
	//	*CommandMsg_IdInfo
	//	*CommandMsg_ArrayIdInfo
	//	*CommandMsg_ArrayChatLog
	Buff isCommandMsg_Buff `protobuf_oneof:"buff"`
}

func (x *CommandMsg) Reset() {
	*x = CommandMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMsg) ProtoMessage() {}

func (x *CommandMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMsg.ProtoReflect.Descriptor instead.
func (*CommandMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *CommandMsg) GetCmdType() ECommand {
	if x != nil {
		return x.CmdType
	}
	return ECommand_SEND_MSG
}

func (x *CommandMsg) GetCmdVal() int32 {
	if x != nil {
		return x.CmdVal
	}
	return 0
}

func (x *CommandMsg) GetCmdStr() string {
	if x != nil {
		return x.CmdStr
	}
	return ""
}

func (m *CommandMsg) GetBuff() isCommandMsg_Buff {
	if m != nil {
		return m.Buff
	}
	return nil
}

func (x *CommandMsg) GetChatMsg() *ChatMsg {
	if x, ok := x.GetBuff().(*CommandMsg_ChatMsg); ok {
		return x.ChatMsg
	}
	return nil
}

func (x *CommandMsg) GetIdInfo() *IdInfo {
	if x, ok := x.GetBuff().(*CommandMsg_IdInfo); ok {
		return x.IdInfo
	}
	return nil
}

func (x *CommandMsg) GetArrayIdInfo() *ArrayIdInfo {
	if x, ok := x.GetBuff().(*CommandMsg_ArrayIdInfo); ok {
		return x.ArrayIdInfo
	}
	return nil
}

func (x *CommandMsg) GetArrayChatLog() *ArrayChatLog {
	if x, ok := x.GetBuff().(*CommandMsg_ArrayChatLog); ok {
		return x.ArrayChatLog
	}
	return nil
}

type isCommandMsg_Buff interface {
	isCommandMsg_Buff()
}

type CommandMsg_ChatMsg struct {
	ChatMsg *ChatMsg `protobuf:"bytes,4,opt,name=chat_msg,json=chatMsg,proto3,oneof"`
}

type CommandMsg_IdInfo struct {
	IdInfo *IdInfo `protobuf:"bytes,5,opt,name=id_info,json=idInfo,proto3,oneof"`
}

type CommandMsg_ArrayIdInfo struct {
	ArrayIdInfo *ArrayIdInfo `protobuf:"bytes,6,opt,name=array_id_info,json=arrayIdInfo,proto3,oneof"`
}

type CommandMsg_ArrayChatLog struct {
	ArrayChatLog *ArrayChatLog `protobuf:"bytes,7,opt,name=array_chat_log,json=arrayChatLog,proto3,oneof"`
}

func (*CommandMsg_ChatMsg) isCommandMsg_Buff() {}

func (*CommandMsg_IdInfo) isCommandMsg_Buff() {}

func (*CommandMsg_ArrayIdInfo) isCommandMsg_Buff() {}

func (*CommandMsg_ArrayChatLog) isCommandMsg_Buff() {}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x22, 0x31, 0x0a, 0x06, 0x49, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0b, 0x41, 0x72, 0x72, 0x61, 0x79, 0x49, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x7c, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x72,
	0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0c, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x28, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0xb1, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x12, 0x27, 0x0a, 0x08, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6d,
	0x64, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6d, 0x64,
	0x56, 0x61, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6d, 0x64, 0x53, 0x74, 0x72, 0x12, 0x28, 0x0a, 0x08,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a,
	0x0d, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x49,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x61, 0x79, 0x49, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x0e, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x48, 0x00,
	0x52, 0x0c, 0x61, 0x72, 0x72, 0x61, 0x79, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x75, 0x66, 0x66, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []interface{}{
	(*ChatMsg)(nil),      // 0: pb.ChatMsg
	(*IdInfo)(nil),       // 1: pb.IdInfo
	(*ArrayIdInfo)(nil),  // 2: pb.ArrayIdInfo
	(*ChatLog)(nil),      // 3: pb.ChatLog
	(*ArrayChatLog)(nil), // 4: pb.ArrayChatLog
	(*CommandMsg)(nil),   // 5: pb.CommandMsg
	(ECommand)(0),        // 6: pb.ECommand
}
var file_message_proto_depIdxs = []int32{
	1, // 0: pb.ArrayIdInfo.id_infos:type_name -> pb.IdInfo
	3, // 1: pb.ArrayChatLog.data_list:type_name -> pb.ChatLog
	6, // 2: pb.CommandMsg.cmd_type:type_name -> pb.ECommand
	0, // 3: pb.CommandMsg.chat_msg:type_name -> pb.ChatMsg
	1, // 4: pb.CommandMsg.id_info:type_name -> pb.IdInfo
	2, // 5: pb.CommandMsg.array_id_info:type_name -> pb.ArrayIdInfo
	4, // 6: pb.CommandMsg.array_chat_log:type_name -> pb.ArrayChatLog
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_commands_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayIdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayChatLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CommandMsg_ChatMsg)(nil),
		(*CommandMsg_IdInfo)(nil),
		(*CommandMsg_ArrayIdInfo)(nil),
		(*CommandMsg_ArrayChatLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
