// Code generated by goctl. DO NOT EDIT!
// Source: auth.proto

package server

import (
	"context"

	"ylink/core/auth/rpc/internal/logic"
	"ylink/core/auth/rpc/internal/svc"
	"ylink/core/auth/rpc/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) PlayerAuth(ctx context.Context, in *pb.PlayerAuthReq) (*pb.AuthResp, error) {
	l := logic.NewPlayerAuthLogic(ctx, s.svcCtx)
	return l.PlayerAuth(in)
}

func (s *AuthServer) CsAuth(ctx context.Context, in *pb.CsAuthReq) (*pb.AuthResp, error) {
	l := logic.NewCsAuthLogic(ctx, s.svcCtx)
	return l.CsAuth(in)
}

func (s *AuthServer) CheckAuth(ctx context.Context, in *pb.CheckAuthReq) (*pb.CheckAuthResp, error) {
	l := logic.NewCheckAuthLogic(ctx, s.svcCtx)
	return l.CheckAuth(in)
}
