// Code generated by goctl. DO NOT EDIT!
// Source: db.proto

package server

import (
	"context"

	"call_center/db/rpc/internal/logic"
	"call_center/db/rpc/internal/svc"
	"call_center/db/rpc/pb"
)

type DbServer struct {
	svcCtx *svc.ServiceContext
}

func NewDbServer(svcCtx *svc.ServiceContext) *DbServer {
	return &DbServer{
		svcCtx: svcCtx,
	}
}

//  客服聊天
func (s *DbServer) DbLogin(stream pb.Db_DbLoginServer) error {
	l := logic.NewDbLoginLogic(stream.Context(), s.svcCtx)
	return l.DbLogin(stream)
}

func (s *DbServer) DbCall(ctx context.Context, in *pb.DbMsgReq) (*pb.DbMsgRes, error) {
	l := logic.NewDbCallLogic(ctx, s.svcCtx)
	return l.DbCall(in)
}

//  游戏聊天
func (s *DbServer) GetSensitiveWords(ctx context.Context, in *pb.SensReq) (*pb.SensRes, error) {
	l := logic.NewGetSensitiveWordsLogic(ctx, s.svcCtx)
	return l.GetSensitiveWords(in)
}
