// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CmdResp) Reset() {
	*x = CmdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResp) ProtoMessage() {}

func (x *CmdResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResp.ProtoReflect.Descriptor instead.
func (*CmdResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *CmdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CmdResp) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

//*
//Player Command Request Bean
type PlayerFetchCsInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
}

func (x *PlayerFetchCsInfoReq) Reset() {
	*x = PlayerFetchCsInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchCsInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchCsInfoReq) ProtoMessage() {}

func (x *PlayerFetchCsInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchCsInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchCsInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerFetchCsInfoReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

type PlayerFetchHistoryMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PlayerFetchHistoryMsgReq) Reset() {
	*x = PlayerFetchHistoryMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchHistoryMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchHistoryMsgReq) ProtoMessage() {}

func (x *PlayerFetchHistoryMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchHistoryMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchHistoryMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerFetchHistoryMsgReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PlayerFetchHistoryMsgReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PlayerFetchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerFetchMsgReq) Reset() {
	*x = PlayerFetchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchMsgReq) ProtoMessage() {}

func (x *PlayerFetchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{3}
}

type PlayerSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Pic     string `protobuf:"bytes,2,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (x *PlayerSendMsgReq) Reset() {
	*x = PlayerSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSendMsgReq) ProtoMessage() {}

func (x *PlayerSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSendMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerSendMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerSendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PlayerSendMsgReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type PlayerDisconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerDisconnectReq) Reset() {
	*x = PlayerDisconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectReq) ProtoMessage() {}

func (x *PlayerDisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectReq.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{5}
}

//*
//Cs Command Request Bean
type CsFetchPlayerQueueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchPlayerQueueReq) Reset() {
	*x = CsFetchPlayerQueueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchPlayerQueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchPlayerQueueReq) ProtoMessage() {}

func (x *CsFetchPlayerQueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchPlayerQueueReq.ProtoReflect.Descriptor instead.
func (*CsFetchPlayerQueueReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *CsFetchPlayerQueueReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsConnectPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *CsConnectPlayerReq) Reset() {
	*x = CsConnectPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConnectPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConnectPlayerReq) ProtoMessage() {}

func (x *CsConnectPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConnectPlayerReq.ProtoReflect.Descriptor instead.
func (*CsConnectPlayerReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *CsConnectPlayerReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsConnectPlayerReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type CsFetchHistoryChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchHistoryChatReq) Reset() {
	*x = CsFetchHistoryChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryChatReq) ProtoMessage() {}

func (x *CsFetchHistoryChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryChatReq.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryChatReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{8}
}

func (x *CsFetchHistoryChatReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CsFetchHistoryChatReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsFetchHistoryMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Page     int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit    int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchHistoryMsgReq) Reset() {
	*x = CsFetchHistoryMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryMsgReq) ProtoMessage() {}

func (x *CsFetchHistoryMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryMsgReq.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{9}
}

func (x *CsFetchHistoryMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsFetchHistoryMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CsFetchHistoryMsgReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CsFetchHistoryMsgReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsFetchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *CsFetchMsgReq) Reset() {
	*x = CsFetchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchMsgReq) ProtoMessage() {}

func (x *CsFetchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchMsgReq.ProtoReflect.Descriptor instead.
func (*CsFetchMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{10}
}

func (x *CsFetchMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsFetchMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type CsSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Pic      string `protobuf:"bytes,4,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (x *CsSendMsgReq) Reset() {
	*x = CsSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsSendMsgReq) ProtoMessage() {}

func (x *CsSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsSendMsgReq.ProtoReflect.Descriptor instead.
func (*CsSendMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *CsSendMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsSendMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CsSendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CsSendMsgReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

var File_pb_cmd_proto protoreflect.FileDescriptor

var file_pb_cmd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5c, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b,
	0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x18, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x22, 0x3e, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x22, 0x2d, 0x0a,
	0x15, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4a, 0x0a, 0x12,
	0x43, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x15, 0x43, 0x73, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x76, 0x0a, 0x14, 0x43,
	0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x0c, 0x43, 0x73,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x32, 0xf3, 0x04, 0x0a,
	0x03, 0x43, 0x6d, 0x64, 0x12, 0x3a, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x42, 0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0d, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38,
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x12, 0x63, 0x73, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0f, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c,
	0x0a, 0x12, 0x63, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x11,
	0x63, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73,
	0x67, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x73, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x09, 0x63, 0x73, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_cmd_proto_rawDescOnce sync.Once
	file_pb_cmd_proto_rawDescData = file_pb_cmd_proto_rawDesc
)

func file_pb_cmd_proto_rawDescGZIP() []byte {
	file_pb_cmd_proto_rawDescOnce.Do(func() {
		file_pb_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_cmd_proto_rawDescData)
	})
	return file_pb_cmd_proto_rawDescData
}

var file_pb_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_cmd_proto_goTypes = []interface{}{
	(*CmdResp)(nil),                  // 0: pb.CmdResp
	(*PlayerFetchCsInfoReq)(nil),     // 1: pb.PlayerFetchCsInfoReq
	(*PlayerFetchHistoryMsgReq)(nil), // 2: pb.PlayerFetchHistoryMsgReq
	(*PlayerFetchMsgReq)(nil),        // 3: pb.PlayerFetchMsgReq
	(*PlayerSendMsgReq)(nil),         // 4: pb.PlayerSendMsgReq
	(*PlayerDisconnectReq)(nil),      // 5: pb.PlayerDisconnectReq
	(*CsFetchPlayerQueueReq)(nil),    // 6: pb.CsFetchPlayerQueueReq
	(*CsConnectPlayerReq)(nil),       // 7: pb.CsConnectPlayerReq
	(*CsFetchHistoryChatReq)(nil),    // 8: pb.CsFetchHistoryChatReq
	(*CsFetchHistoryMsgReq)(nil),     // 9: pb.CsFetchHistoryMsgReq
	(*CsFetchMsgReq)(nil),            // 10: pb.CsFetchMsgReq
	(*CsSendMsgReq)(nil),             // 11: pb.CsSendMsgReq
	(*structpb.Struct)(nil),          // 12: google.protobuf.Struct
}
var file_pb_cmd_proto_depIdxs = []int32{
	12, // 0: pb.CmdResp.data:type_name -> google.protobuf.Struct
	1,  // 1: pb.Cmd.playerFetchCsInfo:input_type -> pb.PlayerFetchCsInfoReq
	2,  // 2: pb.Cmd.playerFetchHistoryMsg:input_type -> pb.PlayerFetchHistoryMsgReq
	3,  // 3: pb.Cmd.playerFetchMsg:input_type -> pb.PlayerFetchMsgReq
	4,  // 4: pb.Cmd.playerSendMsg:input_type -> pb.PlayerSendMsgReq
	5,  // 5: pb.Cmd.playerDisconnect:input_type -> pb.PlayerDisconnectReq
	6,  // 6: pb.Cmd.csFetchPlayerQueue:input_type -> pb.CsFetchPlayerQueueReq
	7,  // 7: pb.Cmd.csConnectPlayer:input_type -> pb.CsConnectPlayerReq
	8,  // 8: pb.Cmd.csFetchHistoryChat:input_type -> pb.CsFetchHistoryChatReq
	9,  // 9: pb.Cmd.csFetchHistoryMsg:input_type -> pb.CsFetchHistoryMsgReq
	10, // 10: pb.Cmd.csFetchMsg:input_type -> pb.CsFetchMsgReq
	11, // 11: pb.Cmd.csSendMsg:input_type -> pb.CsSendMsgReq
	0,  // 12: pb.Cmd.playerFetchCsInfo:output_type -> pb.CmdResp
	0,  // 13: pb.Cmd.playerFetchHistoryMsg:output_type -> pb.CmdResp
	0,  // 14: pb.Cmd.playerFetchMsg:output_type -> pb.CmdResp
	0,  // 15: pb.Cmd.playerSendMsg:output_type -> pb.CmdResp
	0,  // 16: pb.Cmd.playerDisconnect:output_type -> pb.CmdResp
	0,  // 17: pb.Cmd.csFetchPlayerQueue:output_type -> pb.CmdResp
	0,  // 18: pb.Cmd.csConnectPlayer:output_type -> pb.CmdResp
	0,  // 19: pb.Cmd.csFetchHistoryChat:output_type -> pb.CmdResp
	0,  // 20: pb.Cmd.csFetchHistoryMsg:output_type -> pb.CmdResp
	0,  // 21: pb.Cmd.csFetchMsg:output_type -> pb.CmdResp
	0,  // 22: pb.Cmd.csSendMsg:output_type -> pb.CmdResp
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pb_cmd_proto_init() }
func file_pb_cmd_proto_init() {
	if File_pb_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchCsInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchHistoryMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDisconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchPlayerQueueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConnectPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_cmd_proto_goTypes,
		DependencyIndexes: file_pb_cmd_proto_depIdxs,
		MessageInfos:      file_pb_cmd_proto_msgTypes,
	}.Build()
	File_pb_cmd_proto = out.File
	file_pb_cmd_proto_rawDesc = nil
	file_pb_cmd_proto_goTypes = nil
	file_pb_cmd_proto_depIdxs = nil
}
