// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CmdResp) Reset() {
	*x = CmdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResp) ProtoMessage() {}

func (x *CmdResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResp.ProtoReflect.Descriptor instead.
func (*CmdResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *CmdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CmdResp) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

//*
//Player Command Request Bean
type PlayerFetchCsInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CsId     string `protobuf:"bytes,3,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
}

func (x *PlayerFetchCsInfoReq) Reset() {
	*x = PlayerFetchCsInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchCsInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchCsInfoReq) ProtoMessage() {}

func (x *PlayerFetchCsInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchCsInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchCsInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerFetchCsInfoReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerFetchCsInfoReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerFetchCsInfoReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

type PlayerFetchCsInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId         string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	CsNickname   string `protobuf:"bytes,2,opt,name=cs_nickname,json=csNickname,proto3" json:"cs_nickname,omitempty"`
	CsAvatarUrl  string `protobuf:"bytes,3,opt,name=cs_avatar_url,json=csAvatarUrl,proto3" json:"cs_avatar_url,omitempty"`
	CsSignature  string `protobuf:"bytes,4,opt,name=cs_signature,json=csSignature,proto3" json:"cs_signature,omitempty"`
	OnlineStatus int64  `protobuf:"varint,5,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
}

func (x *PlayerFetchCsInfoResp) Reset() {
	*x = PlayerFetchCsInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchCsInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchCsInfoResp) ProtoMessage() {}

func (x *PlayerFetchCsInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchCsInfoResp.ProtoReflect.Descriptor instead.
func (*PlayerFetchCsInfoResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerFetchCsInfoResp) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *PlayerFetchCsInfoResp) GetCsNickname() string {
	if x != nil {
		return x.CsNickname
	}
	return ""
}

func (x *PlayerFetchCsInfoResp) GetCsAvatarUrl() string {
	if x != nil {
		return x.CsAvatarUrl
	}
	return ""
}

func (x *PlayerFetchCsInfoResp) GetCsSignature() string {
	if x != nil {
		return x.CsSignature
	}
	return ""
}

func (x *PlayerFetchCsInfoResp) GetOnlineStatus() int64 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

type PlayerFetchHistoryMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Page     int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit    int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PlayerFetchHistoryMsgReq) Reset() {
	*x = PlayerFetchHistoryMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchHistoryMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchHistoryMsgReq) ProtoMessage() {}

func (x *PlayerFetchHistoryMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchHistoryMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchHistoryMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerFetchHistoryMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerFetchHistoryMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerFetchHistoryMsgReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PlayerFetchHistoryMsgReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PlayerFetchHistoryMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalPage   int64               `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrentPage int64               `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	List        *structpb.ListValue `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *PlayerFetchHistoryMsgResp) Reset() {
	*x = PlayerFetchHistoryMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchHistoryMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchHistoryMsgResp) ProtoMessage() {}

func (x *PlayerFetchHistoryMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchHistoryMsgResp.ProtoReflect.Descriptor instead.
func (*PlayerFetchHistoryMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerFetchHistoryMsgResp) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *PlayerFetchHistoryMsgResp) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PlayerFetchHistoryMsgResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type PlayerFetchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *PlayerFetchMsgReq) Reset() {
	*x = PlayerFetchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchMsgReq) ProtoMessage() {}

func (x *PlayerFetchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerFetchMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerFetchMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerFetchMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type PlayerFetchMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List *structpb.ListValue `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *PlayerFetchMsgResp) Reset() {
	*x = PlayerFetchMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerFetchMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFetchMsgResp) ProtoMessage() {}

func (x *PlayerFetchMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFetchMsgResp.ProtoReflect.Descriptor instead.
func (*PlayerFetchMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerFetchMsgResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type PlayerSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Pic      string `protobuf:"bytes,5,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (x *PlayerSendMsgReq) Reset() {
	*x = PlayerSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSendMsgReq) ProtoMessage() {}

func (x *PlayerSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSendMsgReq.ProtoReflect.Descriptor instead.
func (*PlayerSendMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerSendMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerSendMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerSendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PlayerSendMsgReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type PlayerSendMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerSendMsgResp) Reset() {
	*x = PlayerSendMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerSendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSendMsgResp) ProtoMessage() {}

func (x *PlayerSendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSendMsgResp.ProtoReflect.Descriptor instead.
func (*PlayerSendMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{8}
}

type PlayerDisconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *PlayerDisconnectReq) Reset() {
	*x = PlayerDisconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectReq) ProtoMessage() {}

func (x *PlayerDisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectReq.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerDisconnectReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerDisconnectReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type PlayerDisconnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerDisconnectResp) Reset() {
	*x = PlayerDisconnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDisconnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectResp) ProtoMessage() {}

func (x *PlayerDisconnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectResp.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{10}
}

//*
//Cs Command Request Bean
type CsFetchPlayerQueueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchPlayerQueueReq) Reset() {
	*x = CsFetchPlayerQueueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchPlayerQueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchPlayerQueueReq) ProtoMessage() {}

func (x *CsFetchPlayerQueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchPlayerQueueReq.ProtoReflect.Descriptor instead.
func (*CsFetchPlayerQueueReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *CsFetchPlayerQueueReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsFetchPlayerQueueResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64               `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  *structpb.ListValue `protobuf:"bytes,2,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *CsFetchPlayerQueueResp) Reset() {
	*x = CsFetchPlayerQueueResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchPlayerQueueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchPlayerQueueResp) ProtoMessage() {}

func (x *CsFetchPlayerQueueResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchPlayerQueueResp.ProtoReflect.Descriptor instead.
func (*CsFetchPlayerQueueResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{12}
}

func (x *CsFetchPlayerQueueResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CsFetchPlayerQueueResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CsConnectPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId     string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *CsConnectPlayerReq) Reset() {
	*x = CsConnectPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConnectPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConnectPlayerReq) ProtoMessage() {}

func (x *CsConnectPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConnectPlayerReq.ProtoReflect.Descriptor instead.
func (*CsConnectPlayerReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{13}
}

func (x *CsConnectPlayerReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsConnectPlayerReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsConnectPlayerReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type CsConnectPlayerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsConnectPlayerResp) Reset() {
	*x = CsConnectPlayerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConnectPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConnectPlayerResp) ProtoMessage() {}

func (x *CsConnectPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConnectPlayerResp.ProtoReflect.Descriptor instead.
func (*CsConnectPlayerResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{14}
}

type CsFetchHistoryChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId  string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	Page  int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchHistoryChatReq) Reset() {
	*x = CsFetchHistoryChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryChatReq) ProtoMessage() {}

func (x *CsFetchHistoryChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryChatReq.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryChatReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{15}
}

func (x *CsFetchHistoryChatReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsFetchHistoryChatReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CsFetchHistoryChatReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsFetchHistoryChatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalPage   int64               `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrentPage int64               `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	List        *structpb.ListValue `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *CsFetchHistoryChatResp) Reset() {
	*x = CsFetchHistoryChatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryChatResp) ProtoMessage() {}

func (x *CsFetchHistoryChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryChatResp.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryChatResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{16}
}

func (x *CsFetchHistoryChatResp) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *CsFetchHistoryChatResp) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *CsFetchHistoryChatResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CsFetchHistoryMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId     string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Page     int64  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit    int64  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CsFetchHistoryMsgReq) Reset() {
	*x = CsFetchHistoryMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryMsgReq) ProtoMessage() {}

func (x *CsFetchHistoryMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryMsgReq.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{17}
}

func (x *CsFetchHistoryMsgReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsFetchHistoryMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsFetchHistoryMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CsFetchHistoryMsgReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CsFetchHistoryMsgReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CsFetchHistoryMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId        string              `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	TotalPage   int64               `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrentPage int64               `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	List        *structpb.ListValue `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *CsFetchHistoryMsgResp) Reset() {
	*x = CsFetchHistoryMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchHistoryMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchHistoryMsgResp) ProtoMessage() {}

func (x *CsFetchHistoryMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchHistoryMsgResp.ProtoReflect.Descriptor instead.
func (*CsFetchHistoryMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{18}
}

func (x *CsFetchHistoryMsgResp) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsFetchHistoryMsgResp) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *CsFetchHistoryMsgResp) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *CsFetchHistoryMsgResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CsFetchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId     string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *CsFetchMsgReq) Reset() {
	*x = CsFetchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchMsgReq) ProtoMessage() {}

func (x *CsFetchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchMsgReq.ProtoReflect.Descriptor instead.
func (*CsFetchMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{19}
}

func (x *CsFetchMsgReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsFetchMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsFetchMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type CsFetchMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List *structpb.ListValue `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *CsFetchMsgResp) Reset() {
	*x = CsFetchMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsFetchMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsFetchMsgResp) ProtoMessage() {}

func (x *CsFetchMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsFetchMsgResp.ProtoReflect.Descriptor instead.
func (*CsFetchMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{20}
}

func (x *CsFetchMsgResp) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CsSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsId     string `protobuf:"bytes,1,opt,name=cs_id,json=csId,proto3" json:"cs_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Pic      string `protobuf:"bytes,5,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (x *CsSendMsgReq) Reset() {
	*x = CsSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsSendMsgReq) ProtoMessage() {}

func (x *CsSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsSendMsgReq.ProtoReflect.Descriptor instead.
func (*CsSendMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{21}
}

func (x *CsSendMsgReq) GetCsId() string {
	if x != nil {
		return x.CsId
	}
	return ""
}

func (x *CsSendMsgReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CsSendMsgReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CsSendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CsSendMsgReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type CsSendMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsSendMsgResp) Reset() {
	*x = CsSendMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_cmd_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsSendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsSendMsgResp) ProtoMessage() {}

func (x *CsSendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cmd_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsSendMsgResp.ProtoReflect.Descriptor instead.
func (*CsSendMsgResp) Descriptor() ([]byte, []int) {
	return file_pb_cmd_proto_rawDescGZIP(), []int{22}
}

var File_pb_cmd_proto protoreflect.FileDescriptor

var file_pb_cmd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5c, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61,
	0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05,
	0x63, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49,
	0x64, 0x22, 0xb9, 0x01, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x63,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x73, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x73, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x73, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x73, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7a, 0x0a,
	0x18, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x19, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x11, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x74, 0x0a, 0x10, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63,
	0x22, 0x13, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x73,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5e, 0x0a, 0x16, 0x43, 0x73, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x12, 0x43, 0x73, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x13, 0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x73,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x56, 0x0a, 0x15, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x16, 0x43, 0x73,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x14, 0x43, 0x73, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x13, 0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x13,
	0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x0d, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x40, 0x0a, 0x0e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x43, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x22, 0x0f, 0x0a, 0x0d, 0x43,
	0x73, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x32, 0xfa, 0x05, 0x0a,
	0x03, 0x43, 0x6d, 0x64, 0x12, 0x48, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x43, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54,
	0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12, 0x63, 0x73,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f, 0x63, 0x73, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12, 0x63,
	0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x63, 0x73, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x63, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67,
	0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x73, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x73, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_cmd_proto_rawDescOnce sync.Once
	file_pb_cmd_proto_rawDescData = file_pb_cmd_proto_rawDesc
)

func file_pb_cmd_proto_rawDescGZIP() []byte {
	file_pb_cmd_proto_rawDescOnce.Do(func() {
		file_pb_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_cmd_proto_rawDescData)
	})
	return file_pb_cmd_proto_rawDescData
}

var file_pb_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pb_cmd_proto_goTypes = []interface{}{
	(*CmdResp)(nil),                   // 0: pb.CmdResp
	(*PlayerFetchCsInfoReq)(nil),      // 1: pb.PlayerFetchCsInfoReq
	(*PlayerFetchCsInfoResp)(nil),     // 2: pb.PlayerFetchCsInfoResp
	(*PlayerFetchHistoryMsgReq)(nil),  // 3: pb.PlayerFetchHistoryMsgReq
	(*PlayerFetchHistoryMsgResp)(nil), // 4: pb.PlayerFetchHistoryMsgResp
	(*PlayerFetchMsgReq)(nil),         // 5: pb.PlayerFetchMsgReq
	(*PlayerFetchMsgResp)(nil),        // 6: pb.PlayerFetchMsgResp
	(*PlayerSendMsgReq)(nil),          // 7: pb.PlayerSendMsgReq
	(*PlayerSendMsgResp)(nil),         // 8: pb.PlayerSendMsgResp
	(*PlayerDisconnectReq)(nil),       // 9: pb.PlayerDisconnectReq
	(*PlayerDisconnectResp)(nil),      // 10: pb.PlayerDisconnectResp
	(*CsFetchPlayerQueueReq)(nil),     // 11: pb.CsFetchPlayerQueueReq
	(*CsFetchPlayerQueueResp)(nil),    // 12: pb.CsFetchPlayerQueueResp
	(*CsConnectPlayerReq)(nil),        // 13: pb.CsConnectPlayerReq
	(*CsConnectPlayerResp)(nil),       // 14: pb.CsConnectPlayerResp
	(*CsFetchHistoryChatReq)(nil),     // 15: pb.CsFetchHistoryChatReq
	(*CsFetchHistoryChatResp)(nil),    // 16: pb.CsFetchHistoryChatResp
	(*CsFetchHistoryMsgReq)(nil),      // 17: pb.CsFetchHistoryMsgReq
	(*CsFetchHistoryMsgResp)(nil),     // 18: pb.CsFetchHistoryMsgResp
	(*CsFetchMsgReq)(nil),             // 19: pb.CsFetchMsgReq
	(*CsFetchMsgResp)(nil),            // 20: pb.CsFetchMsgResp
	(*CsSendMsgReq)(nil),              // 21: pb.CsSendMsgReq
	(*CsSendMsgResp)(nil),             // 22: pb.CsSendMsgResp
	(*structpb.Struct)(nil),           // 23: google.protobuf.Struct
	(*structpb.ListValue)(nil),        // 24: google.protobuf.ListValue
}
var file_pb_cmd_proto_depIdxs = []int32{
	23, // 0: pb.CmdResp.data:type_name -> google.protobuf.Struct
	24, // 1: pb.PlayerFetchHistoryMsgResp.list:type_name -> google.protobuf.ListValue
	24, // 2: pb.PlayerFetchMsgResp.list:type_name -> google.protobuf.ListValue
	24, // 3: pb.CsFetchPlayerQueueResp.list:type_name -> google.protobuf.ListValue
	24, // 4: pb.CsFetchHistoryChatResp.list:type_name -> google.protobuf.ListValue
	24, // 5: pb.CsFetchHistoryMsgResp.list:type_name -> google.protobuf.ListValue
	24, // 6: pb.CsFetchMsgResp.list:type_name -> google.protobuf.ListValue
	1,  // 7: pb.Cmd.playerFetchCsInfo:input_type -> pb.PlayerFetchCsInfoReq
	3,  // 8: pb.Cmd.playerFetchHistoryMsg:input_type -> pb.PlayerFetchHistoryMsgReq
	5,  // 9: pb.Cmd.playerFetchMsg:input_type -> pb.PlayerFetchMsgReq
	7,  // 10: pb.Cmd.playerSendMsg:input_type -> pb.PlayerSendMsgReq
	9,  // 11: pb.Cmd.playerDisconnect:input_type -> pb.PlayerDisconnectReq
	11, // 12: pb.Cmd.csFetchPlayerQueue:input_type -> pb.CsFetchPlayerQueueReq
	13, // 13: pb.Cmd.csConnectPlayer:input_type -> pb.CsConnectPlayerReq
	15, // 14: pb.Cmd.csFetchHistoryChat:input_type -> pb.CsFetchHistoryChatReq
	17, // 15: pb.Cmd.csFetchHistoryMsg:input_type -> pb.CsFetchHistoryMsgReq
	19, // 16: pb.Cmd.csFetchMsg:input_type -> pb.CsFetchMsgReq
	21, // 17: pb.Cmd.csSendMsg:input_type -> pb.CsSendMsgReq
	2,  // 18: pb.Cmd.playerFetchCsInfo:output_type -> pb.PlayerFetchCsInfoResp
	4,  // 19: pb.Cmd.playerFetchHistoryMsg:output_type -> pb.PlayerFetchHistoryMsgResp
	6,  // 20: pb.Cmd.playerFetchMsg:output_type -> pb.PlayerFetchMsgResp
	8,  // 21: pb.Cmd.playerSendMsg:output_type -> pb.PlayerSendMsgResp
	10, // 22: pb.Cmd.playerDisconnect:output_type -> pb.PlayerDisconnectResp
	12, // 23: pb.Cmd.csFetchPlayerQueue:output_type -> pb.CsFetchPlayerQueueResp
	14, // 24: pb.Cmd.csConnectPlayer:output_type -> pb.CsConnectPlayerResp
	16, // 25: pb.Cmd.csFetchHistoryChat:output_type -> pb.CsFetchHistoryChatResp
	18, // 26: pb.Cmd.csFetchHistoryMsg:output_type -> pb.CsFetchHistoryMsgResp
	20, // 27: pb.Cmd.csFetchMsg:output_type -> pb.CsFetchMsgResp
	22, // 28: pb.Cmd.csSendMsg:output_type -> pb.CsSendMsgResp
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_cmd_proto_init() }
func file_pb_cmd_proto_init() {
	if File_pb_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchCsInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchCsInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchHistoryMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchHistoryMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerFetchMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerSendMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDisconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDisconnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchPlayerQueueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchPlayerQueueResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConnectPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConnectPlayerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryChatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchHistoryMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsFetchMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_cmd_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsSendMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_cmd_proto_goTypes,
		DependencyIndexes: file_pb_cmd_proto_depIdxs,
		MessageInfos:      file_pb_cmd_proto_msgTypes,
	}.Build()
	File_pb_cmd_proto = out.File
	file_pb_cmd_proto_rawDesc = nil
	file_pb_cmd_proto_goTypes = nil
	file_pb_cmd_proto_depIdxs = nil
}
