// Code generated by goctl. DO NOT EDIT!
// Source: gateway.proto

package gateway

import (
	"context"

	"ylink/gateway/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CsLoginReq     = pb.CsLoginReq
	LoginResp      = pb.LoginResp
	PlayerLoginReq = pb.PlayerLoginReq

	Gateway interface {
		PlayerLogin(ctx context.Context, in *PlayerLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		CsLogin(ctx context.Context, in *CsLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}

func (m *defaultGateway) PlayerLogin(ctx context.Context, in *PlayerLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewGatewayClient(m.cli.Conn())
	return client.PlayerLogin(ctx, in, opts...)
}

func (m *defaultGateway) CsLogin(ctx context.Context, in *CsLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewGatewayClient(m.cli.Conn())
	return client.CsLogin(ctx, in, opts...)
}
