// Code generated by goctl. DO NOT EDIT!
// Source: cmd.proto

package cmd

import (
	"context"

	"ylink/apis/cmd/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CmdResp                  = pb.CmdResp
	CsConnectPlayerReq       = pb.CsConnectPlayerReq
	CsFetchHistoryChatReq    = pb.CsFetchHistoryChatReq
	CsFetchHistoryMsgReq     = pb.CsFetchHistoryMsgReq
	CsFetchMsgReq            = pb.CsFetchMsgReq
	CsFetchPlayerQueueReq    = pb.CsFetchPlayerQueueReq
	CsSendMsgReq             = pb.CsSendMsgReq
	PlayerDisconnectReq      = pb.PlayerDisconnectReq
	PlayerFetchCsInfoReq     = pb.PlayerFetchCsInfoReq
	PlayerFetchHistoryMsgReq = pb.PlayerFetchHistoryMsgReq
	PlayerFetchMsgReq        = pb.PlayerFetchMsgReq
	PlayerSendMsgReq         = pb.PlayerSendMsgReq

	Cmd interface {
		PlayerFetchCsInfo(ctx context.Context, in *PlayerFetchCsInfoReq, opts ...grpc.CallOption) (*CmdResp, error)
		PlayerFetchHistoryMsg(ctx context.Context, in *PlayerFetchHistoryMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
		PlayerFetchMsg(ctx context.Context, in *PlayerFetchMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
		PlayerSendMsg(ctx context.Context, in *PlayerSendMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
		PlayerDisconnect(ctx context.Context, in *PlayerDisconnectReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsFetchPlayerQueue(ctx context.Context, in *CsFetchPlayerQueueReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsConnectPlayer(ctx context.Context, in *CsConnectPlayerReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsFetchHistoryChat(ctx context.Context, in *CsFetchHistoryChatReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsFetchHistoryMsg(ctx context.Context, in *CsFetchHistoryMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsFetchMsg(ctx context.Context, in *CsFetchMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
		CsSendMsg(ctx context.Context, in *CsSendMsgReq, opts ...grpc.CallOption) (*CmdResp, error)
	}

	defaultCmd struct {
		cli zrpc.Client
	}
)

func NewCmd(cli zrpc.Client) Cmd {
	return &defaultCmd{
		cli: cli,
	}
}

func (m *defaultCmd) PlayerFetchCsInfo(ctx context.Context, in *PlayerFetchCsInfoReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.PlayerFetchCsInfo(ctx, in, opts...)
}

func (m *defaultCmd) PlayerFetchHistoryMsg(ctx context.Context, in *PlayerFetchHistoryMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.PlayerFetchHistoryMsg(ctx, in, opts...)
}

func (m *defaultCmd) PlayerFetchMsg(ctx context.Context, in *PlayerFetchMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.PlayerFetchMsg(ctx, in, opts...)
}

func (m *defaultCmd) PlayerSendMsg(ctx context.Context, in *PlayerSendMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.PlayerSendMsg(ctx, in, opts...)
}

func (m *defaultCmd) PlayerDisconnect(ctx context.Context, in *PlayerDisconnectReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.PlayerDisconnect(ctx, in, opts...)
}

func (m *defaultCmd) CsFetchPlayerQueue(ctx context.Context, in *CsFetchPlayerQueueReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsFetchPlayerQueue(ctx, in, opts...)
}

func (m *defaultCmd) CsConnectPlayer(ctx context.Context, in *CsConnectPlayerReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsConnectPlayer(ctx, in, opts...)
}

func (m *defaultCmd) CsFetchHistoryChat(ctx context.Context, in *CsFetchHistoryChatReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsFetchHistoryChat(ctx, in, opts...)
}

func (m *defaultCmd) CsFetchHistoryMsg(ctx context.Context, in *CsFetchHistoryMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsFetchHistoryMsg(ctx, in, opts...)
}

func (m *defaultCmd) CsFetchMsg(ctx context.Context, in *CsFetchMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsFetchMsg(ctx, in, opts...)
}

func (m *defaultCmd) CsSendMsg(ctx context.Context, in *CsSendMsgReq, opts ...grpc.CallOption) (*CmdResp, error) {
	client := pb.NewCmdClient(m.cli.Conn())
	return client.CsSendMsg(ctx, in, opts...)
}
