// Code generated by goctl. DO NOT EDIT!
// Source: rpcbff.proto

package rpcbff

import (
	"context"

	"ylink/bff/rpcbff/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatMsgReq     = pb.ChatMsgReq
	ChatMsgReqResp = pb.ChatMsgReqResp

	Rpcbff interface {
		ReceiverChatMsg(ctx context.Context, in *ChatMsgReq, opts ...grpc.CallOption) (pb.Rpcbff_ReceiverChatMsgClient, error)
	}

	defaultRpcbff struct {
		cli zrpc.Client
	}
)

func NewRpcbff(cli zrpc.Client) Rpcbff {
	return &defaultRpcbff{
		cli: cli,
	}
}

func (m *defaultRpcbff) ReceiverChatMsg(ctx context.Context, in *ChatMsgReq, opts ...grpc.CallOption) (pb.Rpcbff_ReceiverChatMsgClient, error) {
	client := pb.NewRpcbffClient(m.cli.Conn())
	return client.ReceiverChatMsg(ctx, in, opts...)
}
