// Code generated by goctl. DO NOT EDIT.
package types

type PlayerFetchCsInfoReq struct {
	CsId string `json:"cs_id"`
}

type PlayerFetchCsInfoResp struct {
	CsId         string `json:"cs_id"`
	CsNickname   string `json:"cs_nickname"`
	CsAvatarUrl  string `json:"cs_avatar_url"`
	CsSignature  string `json:"cs_signature"`
	OnlineStatus int64  `json:"online_status"`
}

type PlayerFetchHistoryMsgReq struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
}

type PlayerFetchHistoryMsgResp struct {
	TotalPage   int64         `json:"total_page"`
	CurrentPage int64         `json:"current_page"`
	List        []interface{} `json:"list"`
}

type PlayerFetchMsgResp struct {
	List []interface{} `json:"list"`
}

type PlayerSendMsgReq struct {
	Content string `json:"content"`
	Pic     string `json:"pic"`
}

type CsFetchPlayerQueueReq struct {
	Limit int `json:"limit"`
}

type CsFetchPlayerQueueResp struct {
	List []interface{} `json:"list"`
}

type CsConnectPlayerReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
}

type CsFetchHistoryChatReq struct {
	Page  int `json:"page"`
	Limit int `json:"limit"`
}

type CsFetchHistoryChatResp struct {
	TotalPage   int64         `json:"total_page"`
	CurrentPage int64         `json:"current_page"`
	List        []interface{} `json:"list"`
}

type CsFetchHistoryMsgReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
	Page     int    `json:"page"`
	Limit    int    `json:"limit"`
}

type CsFetchHistoryMsgResp struct {
	TotalPage   int64         `json:"total_page"`
	CurrentPage int64         `json:"current_page"`
	List        []interface{} `json:"list"`
}

type CsFetchMsgReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
}

type CsFetchMsgResp struct {
	List []interface{} `json:"list"`
}

type CsSendMsgReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
	Content  string `json:"content"`
	Pic      string `json:"pic"`
}
