// Code generated by goctl. DO NOT EDIT!
// Source: transfer.proto

package transfer

import (
	"context"

	"ylink/core/transfer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TransferReq  = pb.TransferReq
	TransferResp = pb.TransferResp

	Transfer interface {
		Invoke(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	}

	defaultTransfer struct {
		cli zrpc.Client
	}
)

func NewTransfer(cli zrpc.Client) Transfer {
	return &defaultTransfer{
		cli: cli,
	}
}

func (m *defaultTransfer) Invoke(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	client := pb.NewTransferClient(m.cli.Conn())
	return client.Invoke(ctx, in, opts...)
}
