// Code generated by goctl. DO NOT EDIT.
package types

type CommResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type PlayerLoginInfo struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
}

type PlayerConnectReq struct {
	CsId string `json:"cs_id"`
}

type PlayerDisconnectReq struct {
	CsId   string `json:"cs_id"`
	ChatId string `json:"chat_id"`
}

type CsLoginInfo struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CsConnectReq struct {
	PlayerId string `json:"palyer_id"`
	GameId   string `json:"game_id"`
}

type CsDisconnectReq struct {
	PlayerId string `json:"player_id"`
	ChatId   string `json:"chat_id"`
}

type ChatMsgReq struct {
	ChatId string `form:"chat_id"`
	Text   string `form:"msg"`
	Pic    string `form:"pic,optional"`
}
