// Code generated by goctl. DO NOT EDIT.
package types

type PlayerInfo struct {
	Uid    string `json:"uid"`
	GameId string `json:"game_id"`
}

type CsLoginInfo struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CommResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
	RefreshAfter int64  `json:"refresh_after,omitempty"`
}

type SendReq struct {
	Msg string `json:"msg"`
}
