// Code generated by goctl. DO NOT EDIT.
package types

type PlayerAuthReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
}

type CsAuthReq struct {
	CsId string `json:"cs_id"`
}

type AuthResp struct {
	AccessToken string `json:"access_token"`
}
