// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb/rpcbff.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcbffClient is the client API for Rpcbff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcbffClient interface {
	Connect(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (Rpcbff_ConnectClient, error)
	Disconnect(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandResp, error)
}

type rpcbffClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcbffClient(cc grpc.ClientConnInterface) RpcbffClient {
	return &rpcbffClient{cc}
}

func (c *rpcbffClient) Connect(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (Rpcbff_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Rpcbff_ServiceDesc.Streams[0], "/pb.Rpcbff/connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &rpcbffConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rpcbff_ConnectClient interface {
	Recv() (*CommandResp, error)
	grpc.ClientStream
}

type rpcbffConnectClient struct {
	grpc.ClientStream
}

func (x *rpcbffConnectClient) Recv() (*CommandResp, error) {
	m := new(CommandResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rpcbffClient) Disconnect(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandResp, error) {
	out := new(CommandResp)
	err := c.cc.Invoke(ctx, "/pb.Rpcbff/disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcbffServer is the server API for Rpcbff service.
// All implementations must embed UnimplementedRpcbffServer
// for forward compatibility
type RpcbffServer interface {
	Connect(*CommandReq, Rpcbff_ConnectServer) error
	Disconnect(context.Context, *CommandReq) (*CommandResp, error)
	mustEmbedUnimplementedRpcbffServer()
}

// UnimplementedRpcbffServer must be embedded to have forward compatible implementations.
type UnimplementedRpcbffServer struct {
}

func (UnimplementedRpcbffServer) Connect(*CommandReq, Rpcbff_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRpcbffServer) Disconnect(context.Context, *CommandReq) (*CommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedRpcbffServer) mustEmbedUnimplementedRpcbffServer() {}

// UnsafeRpcbffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcbffServer will
// result in compilation errors.
type UnsafeRpcbffServer interface {
	mustEmbedUnimplementedRpcbffServer()
}

func RegisterRpcbffServer(s grpc.ServiceRegistrar, srv RpcbffServer) {
	s.RegisterService(&Rpcbff_ServiceDesc, srv)
}

func _Rpcbff_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcbffServer).Connect(m, &rpcbffConnectServer{stream})
}

type Rpcbff_ConnectServer interface {
	Send(*CommandResp) error
	grpc.ServerStream
}

type rpcbffConnectServer struct {
	grpc.ServerStream
}

func (x *rpcbffConnectServer) Send(m *CommandResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Rpcbff_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcbffServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Rpcbff/disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcbffServer).Disconnect(ctx, req.(*CommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpcbff_ServiceDesc is the grpc.ServiceDesc for Rpcbff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpcbff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Rpcbff",
	HandlerType: (*RpcbffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "disconnect",
			Handler:    _Rpcbff_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "connect",
			Handler:       _Rpcbff_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/rpcbff.proto",
}
