// Code generated by goctl. DO NOT EDIT.
package types

type PlayerAuthReq struct {
	PlayerId string `json:"player_id"`
	GameId   string `json:"game_id"`
}

type CsAuthReq struct {
	CsId string `json:"cs_id"`
}

type CheckAuthReq struct {
	AccessToken string `json:"access_token"`
}

type AuthResp struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
