// Code generated by goctl. DO NOT EDIT!
// Source: rpcbff.proto

package server

import (
	"ylink/bff/rpcbff/internal/logic"
	"ylink/bff/rpcbff/internal/svc"
	"ylink/bff/rpcbff/pb"
)

type RpcbffServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcbffServer
}

func NewRpcbffServer(svcCtx *svc.ServiceContext) *RpcbffServer {
	return &RpcbffServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcbffServer) ReceiverChatMsg(in *pb.ChatMsgReq, stream pb.Rpcbff_ReceiverChatMsgServer) error {
	l := logic.NewReceiverChatMsgLogic(stream.Context(), s.svcCtx)
	return l.ReceiverChatMsg(in, stream)
}
