// Code generated by goctl. DO NOT EDIT!
// Source: rpcbff.proto

package server

import (
	"context"

	"ylink/bff/rpcbff/internal/logic"
	"ylink/bff/rpcbff/internal/svc"
	"ylink/bff/rpcbff/pb"
)

type RpcbffServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcbffServer
}

func NewRpcbffServer(svcCtx *svc.ServiceContext) *RpcbffServer {
	return &RpcbffServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcbffServer) Connect(in *pb.CommandReq, stream pb.Rpcbff_ConnectServer) error {
	l := logic.NewConnectLogic(stream.Context(), s.svcCtx)
	return l.Connect(in, stream)
}

func (s *RpcbffServer) Disconnect(ctx context.Context, in *pb.CommandReq) (*pb.CommandResp, error) {
	l := logic.NewDisconnectLogic(ctx, s.svcCtx)
	return l.Disconnect(in)
}
